# Generated by Django 5.1.4 on 2025-12-25 07:03

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the contact list', max_length=255)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='processing', help_text='Processing status of the list', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible JSONB field for future extensions (file info, stats, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who owns this contact list', on_delete=django.db.models.deletion.CASCADE, related_name='contact_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact List',
                'verbose_name_plural': 'Contact Lists',
                'db_table': 'contact_lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict, help_text='All contact fields stored as JSONB (first_name, email, company, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - deleted contacts remain in DB')),
                ('list', models.ForeignKey(help_text='Contact list this contact belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='lists.contactlist')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_column', models.CharField(help_text='Original column name from CSV/XLSX file', max_length=255)),
                ('mapped_field', models.CharField(help_text="Target field name in contact data (e.g., 'company', 'email')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('list', models.ForeignKey(help_text='Contact list this mapping belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='lists.contactlist')),
            ],
            options={
                'verbose_name': 'Column Mapping',
                'verbose_name_plural': 'Column Mappings',
                'db_table': 'column_mappings',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contactlist',
            index=models.Index(fields=['owner', '-created_at'], name='contact_lis_owner_i_8db98e_idx'),
        ),
        migrations.AddIndex(
            model_name='contactlist',
            index=models.Index(fields=['status', '-created_at'], name='contact_lis_status_abba10_idx'),
        ),
        migrations.AddIndex(
            model_name='contactlist',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='contactlist_metadata_gin'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['list', '-created_at'], name='contacts_list_id_31e376_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['list', 'is_deleted'], name='contacts_list_id_5712a4_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='contact_data_gin'),
        ),
        migrations.AddIndex(
            model_name='columnmapping',
            index=models.Index(fields=['list', 'original_column'], name='column_mapp_list_id_e03c59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='columnmapping',
            unique_together={('list', 'original_column')},
        ),
    ]
