# Generated by Django 5.1.4 on 2025-12-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='Uploaded CSV/XLSX file', null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
