# Generated by Django 5.1.4 on 2025-12-26 16:18

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_contactlist_uploaded_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('user_comment', 'User Comment'), ('system_event', 'System Event'), ('status_change', 'Status Change'), ('field_update', 'Field Update')], db_index=True, default='user_comment', help_text='Type of activity', max_length=20)),
                ('content', models.TextField(help_text='Activity content or comment text')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible JSONB field (edit history, event data, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('is_edited', models.BooleanField(default=False, help_text='True if this comment has been edited')),
                ('author', models.ForeignKey(blank=True, help_text='User who created this activity (null for system events)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(help_text='Contact this activity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='lists.contact')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contact', '-created_at'], name='activities_contact_dbf016_idx'), models.Index(fields=['contact', 'type', '-created_at'], name='activities_contact_c1d7f9_idx'), django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='activity_metadata_gin')],
            },
        ),
    ]
