# Generated by Django 5.1.4 on 2025-12-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColumnMapping',
        ),
    ]
