# Generated by Django 5.1.4 on 2025-12-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_alter_activity_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='in_pipeline',
            field=models.BooleanField(db_index=True, default=False, help_text='Contact is actively being worked on (pipeline)'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['list', 'in_pipeline'], name='contacts_list_id_2d2d09_idx'),
        ),
    ]
