# Generated by Django 5.1.4 on 2025-12-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_contact_in_pipeline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('visit', 'Visit'), ('research', 'Research')], db_index=True, help_text='Type of activity', max_length=20),
        ),
    ]
